// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

global Singleton := {
//               ><warning{':=' to declare a global is deprecated. Remove the ':='}
    callback deinit;
//  >              <error{A global component cannot have a 'deinit' callback}
    deinit => { debug("nope"); }
//  >error{A global component cannot have a 'deinit' callback}
}
//<<<<error{A global component cannot have a 'deinit' callback}

export Test := Rectangle {
//          ><warning{':=' to declare a component is deprecated. The new syntax declare components with 'component MyComponent {'. Read the documentation for more info}
    callback deinit;
//           >    <error{Cannot override callback 'deinit'}
}
